### ISSUE TITLE
能否在reademe中增加代码示例

### ISSUE THREAD

**Issue by 404pnf** [TCL-MIE-CD/fis-parser-art-tmpl#2]
由于自己不熟悉，因此捣鼓了半天才弄明白怎么用。

跑起来后，写了个例子，不知道是否应该这样用。

``` js

// 文件 fis-conf.js
// 在目录tpl中存放模板，模板后缀为html
fis.match('/tpl/**.html', {
    isMod: true,
    release: false
});

// 在app.js中
require(['artTemplate'], function (t) {
    var data = {
        title: '项目文档比较少',
        content: '我捣鼓得好辛苦'
    };
    var render = t.compile(__inline('tpl/text.html'));
    var html = render(data);
    document.getElementById('content').innerHTML = html;
    /* 也可以文艺一点
    document.getElementById('content').innerHTML = t.compile(__inline('tpl/text.html'))({
        title: '项目文档比较少',
        content: '我捣鼓得好辛苦'
    }); */
});
```

如果这个例子是对的，可否在readme中增加类似例子。如果这种用法有问题，能否在readme中举例说明正确用法。帮助我这种小白尽快用起来。谢谢。

**Comment by 404pnf** [comment]
似乎我对本模块的目的理解是错的。

如果按我上面的写法，实际上模板还是在第一次执行代码的时候从字符串编译为js代码。而不是artTemplate自己提供的那种预编译为js代码的效果。

请问本模块能提供inline的是tmod预编译后的结果。谢谢。

**Comment by mmillet** [comment]
这个插件原理很简单，只是简单省去了预编译过程，使用该插件处理后，还是需要依赖art-template的。（而tmod预编译后不需要再依赖art-template。）

这里是用法，比如*.tmpl是模版文件：

```
//fis-conf.js
//匹配模版
.match('/src/**.tmpl', {
  parser: fis.plugin('art-tmpl'),
  rExt: '.js'
}

//业务代码
var artTemplate = require('art-template');
var badgeTmpl = __inline('./tmpl/_badge.tmpl').bind(artTemplate.utils); //需要artTemplate.utils
var data = {};
$('#some-dom').html(badgeTmpl(data));

```

这里有个示例：
http://120.25.62.254:9999/demo/template

**Comment by 404pnf** [comment]
能否实现一个预编译后就不再需要artTemplate的版本？ ：） 

我现在用一个不太妥的方法：

``` js

// fis-conf.js
var spawn = require('child_process').spawn;

var tmod = spawn('tmod', ['./tpl', '--no-watch', '--output', '.']);
tmod.stdout.on('data', console.log);
tmod.stderr.on('data', console.log)
tmod.on('close', console.log);

```

这样tmod将所有模板合并存放在 ./template.js中。

我觉得你这个思路很好，实现也简单。

如果inline进来的代码本身就不是为了可读性而是为了效率，那么是否进一步转为js更合适呢？

**Comment by 404pnf** [comment]
抱歉，我说错了。我按照你的例子实际运行了一下，已经转为和tmod转的一样的东西了。真棒。

我似乎明白为什么目前这个方式很难做到不依赖artTemplate，因此tmod合并后直接把artTemplate的代码写为一个匿名函数放到了合并模板文件的最前面了。

而本项目如果想不依赖就必须每次inline进来模板的是时候也inline进来artTemplate的代码，反而增加代码了。

这个模块就是我想要的。谢谢！
